@endpoint_url = http://localhost:8088
@vault_entry_id = 67deab3abad6b6cc81b7d692
@test_author = user@example.com


### Create a Vault Entry
POST {{endpoint_url}}/create/vault/entry
Content-Type: application/json

{
    "key": "test",
    "value": "ThisShouldBeKeptSecret",
    "created_by": "user@example.com"
}

### Retrieve All Vault Entries
GET {{endpoint_url}}/retrieve/vault/entries

### Retrieve Vault Entry by ID
GET {{endpoint_url}}/retrieve/vault/entries/{{vault_entry_id}}

### Retrieve Vault Entry by Author
GET {{endpoint_url}}/retrieve/vault/entry/{{test_author}}

### Delete a Vault Entry
DELETE {{endpoint_url}}/delete/{{vault_entry_id}}

